spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dsa_tracker
    username: postgres
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update # Auto-creates tables based on your Java entities
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile

jwt:
  secret: ${JWT_SECRET}
  expiration: 604800000

logging:
  level:
    org.springframework.security: DEBUG
